Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-166982.games.s3.yandex.net/166982/gsmxo417bhhx7yqi2s7cwc18xar339zk/index.html?app-id=166982&lang=en#app-id=166982&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1648682578442-28dc&rtx-reqid=8988182564077455946&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=ko__U7ozTm3YPrPQ4L3KHqzq-3y1oUZMJfFVNRdIC9IQfhxfBhl29hV0HEZ_QOBV&experiments=%7B%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22show_disable_ad_button%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=166982
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-166982.games.s3.yandex.net/166982/gsmxo417bhhx7yqi2s7cwc18xar339zk/index.html?app-id=166982&lang=en#app-id=166982&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1648682578442-28dc&rtx-reqid=8988182564077455946&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=ko__U7ozTm3YPrPQ4L3KHqzq-3y1oUZMJfFVNRdIC9IQfhxfBhl29hV0HEZ_QOBV&experiments=%7B%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22show_disable_ad_button%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=166982
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
