Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://uploads.ungrounded.net/alternate/1915000/1915958_alternate_188920_r1.zip/?NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=62df2e929a70b&NewgroundsAPI_SessionID=xvjjYjcxYoUiMhd0nCZr1f21cd9744d9419ad9809ead7c5a7fa170e165d2PYbW&NewgroundsAPI_UserName=rm&NewgroundsAPI_UserID=9962276&ng_username=rm
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://uploads.ungrounded.net/alternate/1915000/1915958_alternate_188920_r1.zip/?NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=62df2e929a70b&NewgroundsAPI_SessionID=xvjjYjcxYoUiMhd0nCZr1f21cd9744d9419ad9809ead7c5a7fa170e165d2PYbW&NewgroundsAPI_UserName=rm&NewgroundsAPI_UserID=9962276&ng_username=rm
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
