Title: Moto X3M
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: 1.1.4f
Languages: en
Extreme: No
Tags: Motocross; Action; Arcade; Physics; Side-Scrolling
Tag Categories: genre; default; default; genre; default
Source: https://www.friv.com/z/games/motox3m/game.html
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://www.friv.com/z/games/motox3m/index-x.html
Game Notes: null
Original Description: It's a sunny day. How about a pleasant little motorcycle
  ride on the beach? What could possibly go wrong?! Try to complete each level
  as quickly as you can (doing stunts will help you) and grab all those stars!
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
