Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://18842.cache.armorgames.com/files/games/factory-balls-foreve-18842/index.html?v=1576488557
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://18842.cache.armorgames.com/files/games/factory-balls-foreve-18842/index.html?v=1576488557
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
