Title: C.A.T.S. - Crash Arena Turbo Stars Playable Ad
Alternate Titles: C.A.T.S. - Crash Arena Turbo Stars Playable Advertisement
Library: arcade
Series: null
Developer: MarketJS
Publisher: MarketJS
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: Action; Advertisement; Demo
Tag Categories: default; default; default
Source: https://cdn-factory.marketjs.com/en/zeptolab-cats-playable-demo/index.html
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://cdn-factory.marketjs.com/en/zeptolab-cats-playable-demo/index.html
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
