Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-178319.games.s3.yandex.net/178319/7jggo4juixbryp1qqr6335vyl1lshi96/index.html?app-id=178319&is-app-page=1&lang=en#app-id=178319&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1649004594069-8988&rtx-reqid=8340099751519526449&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=yR67udL3LEI6QqVGhhxz-kUwLaNajVAM5C1b9nVfM_v0ibqXN7x4RrD70KEajE_U&experiments=%7B%22new_adv_manager%22%3A%22google%22%2C%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22united_page%22%3Atrue%2C%22united_page_same_tab_info%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=178319
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-178319.games.s3.yandex.net/178319/7jggo4juixbryp1qqr6335vyl1lshi96/index.html?app-id=178319&is-app-page=1&lang=en#app-id=178319&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1649004594069-8988&rtx-reqid=8340099751519526449&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=yR67udL3LEI6QqVGhhxz-kUwLaNajVAM5C1b9nVfM_v0ibqXN7x4RrD70KEajE_U&experiments=%7B%22new_adv_manager%22%3A%22google%22%2C%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22united_page%22%3Atrue%2C%22united_page_same_tab_info%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=178319
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
