Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-173327.games.s3.yandex.net/173327/nal30hwrkjctwi8278na3us1gtyfdfkw/index.html#origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=I_gsSkDys6uVRNxH7hlTplarosI06m-Y&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%7D&app-id=173327
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-173327.games.s3.yandex.net/173327/nal30hwrkjctwi8278na3us1gtyfdfkw/index.html#origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=I_gsSkDys6uVRNxH7hlTplarosI06m-Y&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%7D&app-id=173327
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
