Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-98990.games.s3.yandex.net/98990/mj0riikpkul322oqr5eyk5vrjvq1f1dn/index.html?app-id=98990&lang=en#app-id=98990&catalog-session-uid=catalog-e2dcedf0-7988-540f-89e8-3e831561c72d-1644203043358-af4c&rtx-reqid=8068039128392047067&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22games_io%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=iVlurURrqJ9wVFgmCWi3AwUUqR4XwodmddSJFU6G5oP4u3VdhHqrsSKk0481aDZ5fK973H_cdZ9DeYsTsC4kq-JrJXDU0SB3&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22dj_experiment_param%22%3A%228%22%2C%22advm_enabled%22%3A1%2C%22no_ads%22%3Atrue%7D&app-id=98990
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-98990.games.s3.yandex.net/98990/mj0riikpkul322oqr5eyk5vrjvq1f1dn/index.html?app-id=98990&lang=en#app-id=98990&catalog-session-uid=catalog-e2dcedf0-7988-540f-89e8-3e831561c72d-1644203043358-af4c&rtx-reqid=8068039128392047067&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22games_io%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=iVlurURrqJ9wVFgmCWi3AwUUqR4XwodmddSJFU6G5oP4u3VdhHqrsSKk0481aDZ5fK973H_cdZ9DeYsTsC4kq-JrJXDU0SB3&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22dj_experiment_param%22%3A%228%22%2C%22advm_enabled%22%3A1%2C%22no_ads%22%3Atrue%7D&app-id=98990
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
