Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-144506.games.s3.yandex.net/144506/bl9bar1q6etlk3d6uwducphpcx9v24su/index.html?app-id=144506&lang=en&utm_source=game_popup_menu#app-id=144506&catalog-session-uid=catalog-fdad1c44-bd38-5fb4-a90e-a85010bda642-1648491380776-cacd&rtx-reqid=4336469105291956627&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=osCsC6GTwjsy-GSQCFTF5X6BGUppRlKWYdlsEoz70bOnnGLVxnLgasJ1323iwlRzso-Vl2uO-LVnsGF6i2tU4g%2C%2C&experiments=%7B%22anti_adblock_production_cookie%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9952209%2C%22adv_waterfall%22%3Atrue%2C%22adv-block%22%3A%7B%22fullscreen_portrait%22%3A%22R-A-1466359-1%22%2C%22fullscreen%22%3A%22R-A-1466359-3%22%2C%22fullscreen_landscape%22%3A%22R-A-1466359-2%22%7D%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22gpt-adv-block%22%3A%7B%22fullscreen%22%3A%22%2F50008429%2FYandex.Games%2F509832%2FInstream%22%7D%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=144506
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-144506.games.s3.yandex.net/144506/bl9bar1q6etlk3d6uwducphpcx9v24su/index.html?app-id=144506&lang=en&utm_source=game_popup_menu#app-id=144506&catalog-session-uid=catalog-fdad1c44-bd38-5fb4-a90e-a85010bda642-1648491380776-cacd&rtx-reqid=4336469105291956627&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22search%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=osCsC6GTwjsy-GSQCFTF5X6BGUppRlKWYdlsEoz70bOnnGLVxnLgasJ1323iwlRzso-Vl2uO-LVnsGF6i2tU4g%2C%2C&experiments=%7B%22anti_adblock_production_cookie%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9952209%2C%22adv_waterfall%22%3Atrue%2C%22adv-block%22%3A%7B%22fullscreen_portrait%22%3A%22R-A-1466359-1%22%2C%22fullscreen%22%3A%22R-A-1466359-3%22%2C%22fullscreen_landscape%22%3A%22R-A-1466359-2%22%7D%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22gpt-adv-block%22%3A%7B%22fullscreen%22%3A%22%2F50008429%2FYandex.Games%2F509832%2FInstream%22%7D%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=144506
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
