Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-166133.games.s3.yandex.net/166133/cqi8jgft0lonphtppjblvgy1wj0sfr2v/index.html?app-id=166133&lang=en#app-id=166133&catalog-session-uid=catalog-e2dcedf0-7988-540f-89e8-3e831561c72d-1644175667379-d2e8&rtx-reqid=824153487485783732&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=iVlurURrqJ9wVFgmCWi3AwUUqR4XwodmddSJFU6G5oP4u3VdhHqrsSKk0481aDZ5fK973H_cdZ9DeYsTsC4kq-JrJXDU0SB3&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22dj_experiment_param%22%3A%228%22%2C%22advm_enabled%22%3A1%2C%22no_ads%22%3Atrue%7D&app-id=166133&origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=I_gsSkDys6uVRNxH7hlTplarosI06m-Y&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%7D&app-id=166133
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-166133.games.s3.yandex.net/166133/cqi8jgft0lonphtppjblvgy1wj0sfr2v/index.html?app-id=166133&lang=en#app-id=166133&catalog-session-uid=catalog-e2dcedf0-7988-540f-89e8-3e831561c72d-1644175667379-d2e8&rtx-reqid=824153487485783732&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=iVlurURrqJ9wVFgmCWi3AwUUqR4XwodmddSJFU6G5oP4u3VdhHqrsSKk0481aDZ5fK973H_cdZ9DeYsTsC4kq-JrJXDU0SB3&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%2C%22ux_feedback_box_solution_enabled%22%3Atrue%2C%22dj_experiment_param%22%3A%228%22%2C%22advm_enabled%22%3A1%2C%22no_ads%22%3Atrue%7D&app-id=166133&origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=I_gsSkDys6uVRNxH7hlTplarosI06m-Y&experiments=%7B%22gdpr_in_usa%22%3Atrue%2C%22invalidate_games_cache_from%22%3A9086121%2C%22new_trust_form%22%3Atrue%2C%22no_build_change_for_robot%22%3Atrue%7D&app-id=166133
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
