Title: Slope
Alternate Titles: null
Library: arcade
Series: null
Developer: Y8 Studio
Publisher: Y8
Play Mode: Single Player
Release Date: 2014-09-30
Version: null
Languages: en
Extreme: No
Tags: Arcade; Score-Attack; 3D; Dodge
Tag Categories: genre; genre; meta; genre
Source: http://media.y8.com/system/contents/80527/original/slope.unity3d
Platform: Unity
Status: Playable
Application Path: FPSoftware\startUnity.bat
Launch Command: http://media.y8.com/system/contents/80527/original/slope.html
Game Notes: null
Original Description: Speed down a randomized slope. Avoid death for high score.
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
