Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-164455.games.s3.yandex.net/164455/9m5vo2myj6uo9bh0dx1feak3lk87ifmw/index.html?app-id=164455&lang=en#app-id=164455&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1649124164544-dc82&rtx-reqid=15355314889911614736&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22arcade%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=yzYOG3Bh5us5bE2AOhWjEHwCwxKY7Drm3_P2EAvFbA4klnsoKKX-kA%2C%2C&experiments=%7B%22new_adv_manager%22%3A%22google%22%2C%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=164455
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-164455.games.s3.yandex.net/164455/9m5vo2myj6uo9bh0dx1feak3lk87ifmw/index.html?app-id=164455&lang=en#app-id=164455&catalog-session-uid=catalog-06040a72-f2a9-5480-a495-f265bdadc76d-1649124164544-dc82&rtx-reqid=15355314889911614736&pos=%7B%22listType%22%3A%22suggested%22%2C%22tabCategory%22%3A%22arcade%22%7D&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=yzYOG3Bh5us5bE2AOhWjEHwCwxKY7Drm3_P2EAvFbA4klnsoKKX-kA%2C%2C&experiments=%7B%22new_adv_manager%22%3A%22google%22%2C%22invalidate_games_cache_from%22%3A9952209%2C%22homeland_currency_basket%22%3Atrue%2C%22no_ads%22%3Atrue%2C%22auth_manager%22%3Atrue%2C%22recovery_code%22%3Atrue%2C%22merge_conflicts%22%3Atrue%2C%22payments_igames%22%3Atrue%2C%22new_unauthorized_cookie%22%3Atrue%7D&app-id=164455
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
